version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - spring-network
    container_name: spring-boot-hello-world

networks:
  spring-network:
    driver: bridge
